# Derived from galago-tools interfaces/tools/grpc_interfaces/alps3000.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/alps3000.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/alps3000.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:rhylthyme_galago/_gen/tools/grpc_interfaces/alps3000.proto\x12\x32\x63om.science.foundry.tools.grpc_interfaces.alps3000\"\x9d\x08\n\x07\x43ommand\x12\x65\n\nget_status\x18\x01 \x01(\x0b\x32O.com.science.foundry.tools.grpc_interfaces.alps3000.Command.GetInstrumentStatusH\x00\x12[\n\nseal_plate\x18\x02 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.alps3000.Command.SealPlateH\x00\x12Y\n\tget_error\x18\x03 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.alps3000.Command.GetErrorH\x00\x12\x65\n\x0fset_temperature\x18\x04 \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.alps3000.Command.SetTemperatureH\x00\x12\x63\n\x10set_sealing_time\x18\x05 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.alps3000.Command.SetSealTimeH\x00\x12~\n get_sealing_temperature_setpoint\x18\x06 \x01(\x0b\x32R.com.science.foundry.tools.grpc_interfaces.alps3000.Command.GetTemperatureSetpointH\x00\x12\x63\n\x10get_sealing_time\x18\x07 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.alps3000.Command.SetSealTimeH\x00\x12z\n\x1eget_sealing_temperature_actual\x18\x08 \x01(\x0b\x32P.com.science.foundry.tools.grpc_interfaces.alps3000.Command.GetTemperatureActualH\x00\x1a%\n\x0eSetTemperature\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\x1a \n\x0bSetSealTime\x12\x11\n\tseal_time\x18\x01 \x01(\x05\x1a\x15\n\x13GetInstrumentStatus\x1a\x0b\n\tSealPlate\x1a\n\n\x08GetError\x1a\x16\n\x14GetTemperatureActual\x1a\x10\n\x0eGetSealingTime\x1a\x18\n\x16GetTemperatureSetpointB\t\n\x07\x63ommand\"+\n\x06\x43onfig\x12\x0f\n\x07profile\x18\x01 \x01(\t\x12\x10\n\x08\x63om_port\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.alps3000_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=115
  _globals['_COMMAND']._serialized_end=1168
  _globals['_COMMAND_SETTEMPERATURE']._serialized_start=970
  _globals['_COMMAND_SETTEMPERATURE']._serialized_end=1007
  _globals['_COMMAND_SETSEALTIME']._serialized_start=1009
  _globals['_COMMAND_SETSEALTIME']._serialized_end=1041
  _globals['_COMMAND_GETINSTRUMENTSTATUS']._serialized_start=1043
  _globals['_COMMAND_GETINSTRUMENTSTATUS']._serialized_end=1064
  _globals['_COMMAND_SEALPLATE']._serialized_start=1066
  _globals['_COMMAND_SEALPLATE']._serialized_end=1077
  _globals['_COMMAND_GETERROR']._serialized_start=1079
  _globals['_COMMAND_GETERROR']._serialized_end=1089
  _globals['_COMMAND_GETTEMPERATUREACTUAL']._serialized_start=1091
  _globals['_COMMAND_GETTEMPERATUREACTUAL']._serialized_end=1113
  _globals['_COMMAND_GETSEALINGTIME']._serialized_start=1115
  _globals['_COMMAND_GETSEALINGTIME']._serialized_end=1131
  _globals['_COMMAND_GETTEMPERATURESETPOINT']._serialized_start=1133
  _globals['_COMMAND_GETTEMPERATURESETPOINT']._serialized_end=1157
  _globals['_CONFIG']._serialized_start=1170
  _globals['_CONFIG']._serialized_end=1213
# @@protoc_insertion_point(module_scope)
