# Derived from galago-tools interfaces/tools/grpc_interfaces/bioshake.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/bioshake.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/bioshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:rhylthyme_galago/_gen/tools/grpc_interfaces/bioshake.proto\x12\x32\x63om.science.foundry.tools.grpc_interfaces.bioshake\"\xaf\t\n\x07\x43ommand\x12P\n\x04grip\x18\x01 \x01(\x0b\x32@.com.science.foundry.tools.grpc_interfaces.bioshake.Command.GripH\x00\x12T\n\x06ungrip\x18\x02 \x01(\x0b\x32\x42.com.science.foundry.tools.grpc_interfaces.bioshake.Command.UngripH\x00\x12P\n\x04home\x18\x03 \x01(\x0b\x32@.com.science.foundry.tools.grpc_interfaces.bioshake.Command.HomeH\x00\x12]\n\x0bstart_shake\x18\x04 \x01(\x0b\x32\x46.com.science.foundry.tools.grpc_interfaces.bioshake.Command.StartShakeH\x00\x12[\n\nstop_shake\x18\x05 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.bioshake.Command.StopShakeH\x00\x12R\n\x05reset\x18\x06 \x01(\x0b\x32\x41.com.science.foundry.tools.grpc_interfaces.bioshake.Command.ResetH\x00\x12t\n\x18wait_for_shake_to_finish\x18\x07 \x01(\x0b\x32P.com.science.foundry.tools.grpc_interfaces.bioshake.Command.WaitForShakeToFinishH\x00\x12\x65\n\x0fset_temperature\x18\x08 \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.bioshake.Command.SetTemperatureH\x00\x12\x63\n\x0etemperature_on\x18\t \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.bioshake.Command.TemperatureOnH\x00\x12\x65\n\x0ftemperature_off\x18\n \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.bioshake.Command.TemperatureOffH\x00\x1a\x06\n\x04Grip\x1a\x08\n\x06Ungrip\x1a\x06\n\x04Home\x1a\x43\n\nStartShake\x12\r\n\x05speed\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x05\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x1a\x0b\n\tStopShake\x1a\x07\n\x05Reset\x1a\'\n\x14WaitForShakeToFinish\x12\x0f\n\x07timeout\x18\x01 \x01(\x05\x1a\x0f\n\rTemperatureOn\x1a\x10\n\x0eTemperatureOff\x1a%\n\x0eSetTemperature\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\x42\t\n\x07\x63ommand\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x63om_port\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.bioshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=115
  _globals['_COMMAND']._serialized_end=1314
  _globals['_COMMAND_GRIP']._serialized_start=1073
  _globals['_COMMAND_GRIP']._serialized_end=1079
  _globals['_COMMAND_UNGRIP']._serialized_start=1081
  _globals['_COMMAND_UNGRIP']._serialized_end=1089
  _globals['_COMMAND_HOME']._serialized_start=1091
  _globals['_COMMAND_HOME']._serialized_end=1097
  _globals['_COMMAND_STARTSHAKE']._serialized_start=1099
  _globals['_COMMAND_STARTSHAKE']._serialized_end=1166
  _globals['_COMMAND_STOPSHAKE']._serialized_start=1168
  _globals['_COMMAND_STOPSHAKE']._serialized_end=1179
  _globals['_COMMAND_RESET']._serialized_start=1181
  _globals['_COMMAND_RESET']._serialized_end=1188
  _globals['_COMMAND_WAITFORSHAKETOFINISH']._serialized_start=1190
  _globals['_COMMAND_WAITFORSHAKETOFINISH']._serialized_end=1229
  _globals['_COMMAND_TEMPERATUREON']._serialized_start=1231
  _globals['_COMMAND_TEMPERATUREON']._serialized_end=1246
  _globals['_COMMAND_TEMPERATUREOFF']._serialized_start=1248
  _globals['_COMMAND_TEMPERATUREOFF']._serialized_end=1264
  _globals['_COMMAND_SETTEMPERATURE']._serialized_start=1266
  _globals['_COMMAND_SETTEMPERATURE']._serialized_end=1303
  _globals['_CONFIG']._serialized_start=1316
  _globals['_CONFIG']._serialized_end=1342
# @@protoc_insertion_point(module_scope)
