# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/bravo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/bravo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7rhylthyme_galago/_gen/tools/grpc_interfaces/bravo.proto\x12/com.science.foundry.tools.grpc_interfaces.bravo\"\xfd\x02\n\x07\x43ommand\x12Y\n\ninitialize\x18\x01 \x01(\x0b\x32\x43.com.science.foundry.tools.grpc_interfaces.bravo.Command.InitializeH\x00\x12\\\n\x0crun_protocol\x18\x02 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.bravo.Command.RunProtocolH\x00\x12X\n\nrun_runset\x18\x03 \x01(\x0b\x32\x42.com.science.foundry.tools.grpc_interfaces.bravo.Command.RunRunsetH\x00\x1a\x0c\n\nInitialize\x1a$\n\x0bRunProtocol\x12\x15\n\rprotocol_file\x18\x01 \x01(\t\x1a \n\tRunRunset\x12\x13\n\x0brunset_file\x18\x01 \x01(\tB\t\n\x07\x63ommand\"\x1d\n\x06\x43onfig\x12\x13\n\x0b\x64\x65vice_file\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.bravo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=109
  _globals['_COMMAND']._serialized_end=490
  _globals['_COMMAND_INITIALIZE']._serialized_start=395
  _globals['_COMMAND_INITIALIZE']._serialized_end=407
  _globals['_COMMAND_RUNPROTOCOL']._serialized_start=409
  _globals['_COMMAND_RUNPROTOCOL']._serialized_end=445
  _globals['_COMMAND_RUNRUNSET']._serialized_start=447
  _globals['_COMMAND_RUNRUNSET']._serialized_end=479
  _globals['_CONFIG']._serialized_start=492
  _globals['_CONFIG']._serialized_end=521
# @@protoc_insertion_point(module_scope)
