# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/clariostar.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/clariostar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<rhylthyme_galago/_gen/tools/grpc_interfaces/clariostar.proto\x12\x34\x63om.science.foundry.tools.grpc_interfaces.clariostar\"\xfd\x04\n\x07\x43ommand\x12\x61\n\x0copen_carrier\x18\x01 \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.clariostar.Command.OpenCarrierH\x00\x12\x63\n\rclose_carrier\x18\x02 \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.clariostar.Command.CloseCarrierH\x00\x12]\n\nstart_read\x18\x03 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.clariostar.Command.StartReadH\x00\x12g\n\x0fset_temperature\x18\x04 \x01(\x0b\x32L.com.science.foundry.tools.grpc_interfaces.clariostar.Command.SetTemperatureH\x00\x1a\r\n\x0bOpenCarrier\x1a\x0e\n\x0c\x43loseCarrier\x1a\x90\x01\n\tStartRead\x12\x15\n\rprotocol_name\x18\x01 \x01(\t\x12\x15\n\x08plate_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x61ssay_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\ttimepoint\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x0b\n\t_plate_idB\x0b\n\t_assay_idB\x0c\n\n_timepoint\x1a%\n\x0eSetTemperature\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x42\t\n\x07\x63ommand\"Y\n\x06\x43onfig\x12\x14\n\x0cprotocol_dir\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_dir\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\x12\x12\n\noutput_dir\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.clariostar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=119
  _globals['_COMMAND']._serialized_end=756
  _globals['_COMMAND_OPENCARRIER']._serialized_start=530
  _globals['_COMMAND_OPENCARRIER']._serialized_end=543
  _globals['_COMMAND_CLOSECARRIER']._serialized_start=545
  _globals['_COMMAND_CLOSECARRIER']._serialized_end=559
  _globals['_COMMAND_STARTREAD']._serialized_start=562
  _globals['_COMMAND_STARTREAD']._serialized_end=706
  _globals['_COMMAND_SETTEMPERATURE']._serialized_start=708
  _globals['_COMMAND_SETTEMPERATURE']._serialized_end=745
  _globals['_CONFIG']._serialized_start=758
  _globals['_CONFIG']._serialized_end=847
# @@protoc_insertion_point(module_scope)
