# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/dataman70.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/dataman70.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;rhylthyme_galago/_gen/tools/grpc_interfaces/dataman70.proto\x12\x33\x63om.science.foundry.tools.grpc_interfaces.dataman70\"\x90\x02\n\x07\x43ommand\x12Q\n\x04scan\x18\x01 \x01(\x0b\x32\x41.com.science.foundry.tools.grpc_interfaces.dataman70.Command.ScanH\x00\x12\x64\n\x0e\x61ssert_barcode\x18\x02 \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.dataman70.Command.AssertBarcodeH\x00\x1a\x1f\n\x04Scan\x12\x17\n\x0fmapped_variable\x18\x01 \x01(\t\x1a \n\rAssertBarcode\x12\x0f\n\x07\x62\x61rcode\x18\x01 \x01(\tB\t\n\x07\x63ommand\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x63om_port\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.dataman70_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=117
  _globals['_COMMAND']._serialized_end=389
  _globals['_COMMAND_SCAN']._serialized_start=313
  _globals['_COMMAND_SCAN']._serialized_end=344
  _globals['_COMMAND_ASSERTBARCODE']._serialized_start=346
  _globals['_COMMAND_ASSERTBARCODE']._serialized_end=378
  _globals['_CONFIG']._serialized_start=391
  _globals['_CONFIG']._serialized_end=417
# @@protoc_insertion_point(module_scope)
