# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/hamilton.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/hamilton.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:rhylthyme_galago/_gen/tools/grpc_interfaces/hamilton.proto\x12\x32\x63om.science.foundry.tools.grpc_interfaces.hamilton\"\x9b\x02\n\x07\x43ommand\x12_\n\x0crun_protocol\x18\x01 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.hamilton.Command.RunProtocolH\x00\x12\x61\n\rload_protocol\x18\x02 \x01(\x0b\x32H.com.science.foundry.tools.grpc_interfaces.hamilton.Command.LoadProtocolH\x00\x1a\x1f\n\x0bRunProtocol\x12\x10\n\x08protocol\x18\x01 \x01(\t\x1a \n\x0cLoadProtocol\x12\x10\n\x08protocol\x18\x01 \x01(\tB\t\n\x07\x63ommand\"\x08\n\x06\x43onfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.hamilton_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=115
  _globals['_COMMAND']._serialized_end=398
  _globals['_COMMAND_RUNPROTOCOL']._serialized_start=322
  _globals['_COMMAND_RUNPROTOCOL']._serialized_end=353
  _globals['_COMMAND_LOADPROTOCOL']._serialized_start=355
  _globals['_COMMAND_LOADPROTOCOL']._serialized_end=387
  _globals['_CONFIG']._serialized_start=400
  _globals['_CONFIG']._serialized_end=408
# @@protoc_insertion_point(module_scope)
