# Derived from galago-tools interfaces/tools/grpc_interfaces/hig_centrifuge.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/hig_centrifuge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/hig_centrifuge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@rhylthyme_galago/_gen/tools/grpc_interfaces/hig_centrifuge.proto\x12\x38\x63om.science.foundry.tools.grpc_interfaces.hig_centrifuge\"\xa7\x05\n\x07\x43ommand\x12V\n\x04home\x18\x01 \x01(\x0b\x32\x46.com.science.foundry.tools.grpc_interfaces.hig_centrifuge.Command.HomeH\x00\x12\x65\n\x0c\x63lose_shield\x18\x02 \x01(\x0b\x32M.com.science.foundry.tools.grpc_interfaces.hig_centrifuge.Command.CloseShieldH\x00\x12\x63\n\x0bopen_shield\x18\x03 \x01(\x0b\x32L.com.science.foundry.tools.grpc_interfaces.hig_centrifuge.Command.OpenShieldH\x00\x12V\n\x04spin\x18\x04 \x01(\x0b\x32\x46.com.science.foundry.tools.grpc_interfaces.hig_centrifuge.Command.SpinH\x00\x12\x63\n\x0bhome_shield\x18\x05 \x01(\x0b\x32L.com.science.foundry.tools.grpc_interfaces.hig_centrifuge.Command.HomeShieldH\x00\x1a\x06\n\x04Home\x1a\r\n\x0b\x43loseShield\x1a\x1f\n\nOpenShield\x12\x11\n\tbucket_id\x18\x01 \x01(\x05\x1aT\n\x04Spin\x12\r\n\x05speed\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x05\x12\x15\n\rdecceleration\x18\x03 \x01(\x05\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x1a\x0b\n\tAbortSpin\x1a\x07\n\x05Reset\x1a\x0c\n\nHomeShieldB\t\n\x07\x63ommand\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x63\x61n_port\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.hig_centrifuge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=127
  _globals['_COMMAND']._serialized_end=806
  _globals['_COMMAND_HOME']._serialized_start=619
  _globals['_COMMAND_HOME']._serialized_end=625
  _globals['_COMMAND_CLOSESHIELD']._serialized_start=627
  _globals['_COMMAND_CLOSESHIELD']._serialized_end=640
  _globals['_COMMAND_OPENSHIELD']._serialized_start=642
  _globals['_COMMAND_OPENSHIELD']._serialized_end=673
  _globals['_COMMAND_SPIN']._serialized_start=675
  _globals['_COMMAND_SPIN']._serialized_end=759
  _globals['_COMMAND_ABORTSPIN']._serialized_start=761
  _globals['_COMMAND_ABORTSPIN']._serialized_end=772
  _globals['_COMMAND_RESET']._serialized_start=774
  _globals['_COMMAND_RESET']._serialized_end=781
  _globals['_COMMAND_HOMESHIELD']._serialized_start=783
  _globals['_COMMAND_HOMESHIELD']._serialized_end=795
  _globals['_CONFIG']._serialized_start=808
  _globals['_CONFIG']._serialized_end=834
# @@protoc_insertion_point(module_scope)
