# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/labware.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/labware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9rhylthyme_galago/_gen/tools/grpc_interfaces/labware.proto\x12\x31\x63om.science.foundry.tools.grpc_interfaces.labware\"\x84\x02\n\x07Labware\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x16\n\x0enumber_of_rows\x18\x05 \x01(\x05\x12\x19\n\x11number_of_columns\x18\x06 \x01(\x05\x12\x10\n\x08z_offset\x18\x07 \x01(\x02\x12\r\n\x05width\x18\x08 \x01(\x02\x12\x0e\n\x06height\x18\t \x01(\x02\x12\x18\n\x10plate_lid_offset\x18\n \x01(\x02\x12\x12\n\nlid_offset\x18\x0b \x01(\x02\x12\x14\n\x0cstack_height\x18\x0c \x01(\x02\x12\x0f\n\x07has_lid\x18\r \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.labware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABWARE']._serialized_start=113
  _globals['_LABWARE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
