# Derived from galago-tools interfaces/tools/grpc_interfaces/lcus1_relay.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/lcus1_relay.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/lcus1_relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=rhylthyme_galago/_gen/tools/grpc_interfaces/lcus1_relay.proto\x12\x35\x63om.science.foundry.tools.grpc_interfaces.lcus1_relay\"\x90\x02\n\x07\x43ommand\x12W\n\x06switch\x18\x01 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.lcus1_relay.Command.SwitchH\x00\x12\x62\n\x0ctimed_switch\x18\x02 \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.lcus1_relay.Command.TimedSwitchH\x00\x1a\x14\n\x06Switch\x12\n\n\x02on\x18\x01 \x01(\x08\x1a\'\n\x0bTimedSwitch\x12\x18\n\x10\x64uration_seconds\x18\x01 \x01(\x02\x42\t\n\x07\x63ommand\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x63om_port\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.lcus1_relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=121
  _globals['_COMMAND']._serialized_end=393
  _globals['_COMMAND_SWITCH']._serialized_start=321
  _globals['_COMMAND_SWITCH']._serialized_end=341
  _globals['_COMMAND_TIMEDSWITCH']._serialized_start=343
  _globals['_COMMAND_TIMEDSWITCH']._serialized_end=382
  _globals['_CONFIG']._serialized_start=395
  _globals['_CONFIG']._serialized_end=421
# @@protoc_insertion_point(module_scope)
