# Derived from galago-tools interfaces/tools/grpc_interfaces/liconic.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/liconic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/liconic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9rhylthyme_galago/_gen/tools/grpc_interfaces/liconic.proto\x12\x31\x63om.science.foundry.tools.grpc_interfaces.liconic\"\xd7\x04\n\x07\x43ommand\x12\\\n\x0b\x66\x65tch_plate\x18\x01 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.liconic.Command.FetchPlateH\x00\x12\\\n\x0bstore_plate\x18\x02 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.liconic.Command.StorePlateH\x00\x12Q\n\x05reset\x18\x03 \x01(\x0b\x32@.com.science.foundry.tools.grpc_interfaces.liconic.Command.ResetH\x00\x12`\n\x0braw_command\x18\x04 \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.liconic.Command.SendRawCommandH\x00\x1aS\n\nFetchPlate\x12\x10\n\x08\x63\x61ssette\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x16\n\twait_time\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x0c\n\n_wait_time\x1aS\n\nStorePlate\x12\x10\n\x08\x63\x61ssette\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x16\n\twait_time\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x0c\n\n_wait_time\x1a\x1d\n\x0eSendRawCommand\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x1a\x07\n\x05ResetB\t\n\x07\x63ommand\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x63om_port\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.liconic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=113
  _globals['_COMMAND']._serialized_end=712
  _globals['_COMMAND_FETCHPLATE']._serialized_start=493
  _globals['_COMMAND_FETCHPLATE']._serialized_end=576
  _globals['_COMMAND_STOREPLATE']._serialized_start=578
  _globals['_COMMAND_STOREPLATE']._serialized_end=661
  _globals['_COMMAND_SENDRAWCOMMAND']._serialized_start=663
  _globals['_COMMAND_SENDRAWCOMMAND']._serialized_end=692
  _globals['_COMMAND_RESET']._serialized_start=694
  _globals['_COMMAND_RESET']._serialized_end=701
  _globals['_CONFIG']._serialized_start=714
  _globals['_CONFIG']._serialized_end=740
# @@protoc_insertion_point(module_scope)
