# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/microserve.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/microserve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<rhylthyme_galago/_gen/tools/grpc_interfaces/microserve.proto\x12\x34\x63om.science.foundry.tools.grpc_interfaces.microserve\"\x97\x07\n\x07\x43ommand\x12R\n\x04load\x18\x01 \x01(\x0b\x32\x42.com.science.foundry.tools.grpc_interfaces.microserve.Command.LoadH\x00\x12V\n\x06unload\x18\x02 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.microserve.Command.UnloadH\x00\x12R\n\x04home\x18\x03 \x01(\x0b\x32\x42.com.science.foundry.tools.grpc_interfaces.microserve.Command.HomeH\x00\x12T\n\x05\x61\x62ort\x18\x04 \x01(\x0b\x32\x43.com.science.foundry.tools.grpc_interfaces.microserve.Command.AbortH\x00\x12X\n\x07retract\x18\x05 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.microserve.Command.RetractH\x00\x12S\n\x05go_to\x18\x06 \x01(\x0b\x32\x42.com.science.foundry.tools.grpc_interfaces.microserve.Command.GoToH\x00\x12\x63\n\x0braw_command\x18\x08 \x01(\x0b\x32L.com.science.foundry.tools.grpc_interfaces.microserve.Command.SendRawCommandH\x00\x1a]\n\x04Load\x12\x10\n\x08stack_id\x18\x01 \x01(\x05\x12\x14\n\x0cplate_height\x18\x02 \x01(\x02\x12\x14\n\x0cstack_height\x18\x03 \x01(\x02\x12\x17\n\x0fplate_thickness\x18\x04 \x01(\x02\x1a_\n\x06Unload\x12\x10\n\x08stack_id\x18\x01 \x01(\x05\x12\x14\n\x0cplate_height\x18\x02 \x01(\x02\x12\x14\n\x0cstack_height\x18\x03 \x01(\x02\x12\x17\n\x0fplate_thickness\x18\x04 \x01(\x02\x1a\x06\n\x04Home\x1a\x07\n\x05\x41\x62ort\x1a\t\n\x07Retract\x1a\x18\n\x04GoTo\x12\x10\n\x08stack_id\x18\x01 \x01(\x05\x1a!\n\x0eSendRawCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\tB\t\n\x07\x63ommand\"\"\n\x06\x43onfig\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.microserve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=119
  _globals['_COMMAND']._serialized_end=1038
  _globals['_COMMAND_LOAD']._serialized_start=748
  _globals['_COMMAND_LOAD']._serialized_end=841
  _globals['_COMMAND_UNLOAD']._serialized_start=843
  _globals['_COMMAND_UNLOAD']._serialized_end=938
  _globals['_COMMAND_HOME']._serialized_start=940
  _globals['_COMMAND_HOME']._serialized_end=946
  _globals['_COMMAND_ABORT']._serialized_start=948
  _globals['_COMMAND_ABORT']._serialized_end=955
  _globals['_COMMAND_RETRACT']._serialized_start=957
  _globals['_COMMAND_RETRACT']._serialized_end=966
  _globals['_COMMAND_GOTO']._serialized_start=968
  _globals['_COMMAND_GOTO']._serialized_end=992
  _globals['_COMMAND_SENDRAWCOMMAND']._serialized_start=994
  _globals['_COMMAND_SENDRAWCOMMAND']._serialized_end=1027
  _globals['_CONFIG']._serialized_start=1040
  _globals['_CONFIG']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
