# Derived from galago-tools interfaces/tools/grpc_interfaces/multidrop.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/multidrop.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/multidrop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;rhylthyme_galago/_gen/tools/grpc_interfaces/multidrop.proto\x12\x33\x63om.science.foundry.tools.grpc_interfaces.multidrop\"\xd6\x01\n\x07\x43ommand\x12Q\n\x04home\x18\x01 \x01(\x0b\x32\x41.com.science.foundry.tools.grpc_interfaces.multidrop.Command.HomeH\x00\x12Y\n\x08\x64ispense\x18\x02 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.multidrop.Command.DispenseH\x00\x1a\x06\n\x04Home\x1a\n\n\x08\x44ispenseB\t\n\x07\x63ommand\"\x16\n\x06\x43onfig\x12\x0c\n\x04port\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.multidrop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=117
  _globals['_COMMAND']._serialized_end=331
  _globals['_COMMAND_HOME']._serialized_start=302
  _globals['_COMMAND_HOME']._serialized_end=308
  _globals['_COMMAND_DISPENSE']._serialized_start=310
  _globals['_COMMAND_DISPENSE']._serialized_end=320
  _globals['_CONFIG']._serialized_start=333
  _globals['_CONFIG']._serialized_end=355
# @@protoc_insertion_point(module_scope)
