# Derived from galago-tools interfaces/tools/grpc_interfaces/opentrons2.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/opentrons2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/opentrons2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<rhylthyme_galago/_gen/tools/grpc_interfaces/opentrons2.proto\x12\x34\x63om.science.foundry.tools.grpc_interfaces.opentrons2\x1a\x1cgoogle/protobuf/struct.proto\"\xdc\x04\n\x07\x43ommand\x12_\n\x0brun_program\x18\x01 \x01(\x0b\x32H.com.science.foundry.tools.grpc_interfaces.opentrons2.Command.RunProgramH\x00\x12T\n\x05pause\x18\x02 \x01(\x0b\x32\x43.com.science.foundry.tools.grpc_interfaces.opentrons2.Command.PauseH\x00\x12V\n\x06resume\x18\x03 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.opentrons2.Command.ResumeH\x00\x12V\n\x06\x63\x61ncel\x18\x04 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.opentrons2.Command.CancelH\x00\x12\x61\n\x0ctoggle_light\x18\x05 \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.opentrons2.Command.ToggleLightH\x00\x1aP\n\nRunProgram\x12\x16\n\x0escript_content\x18\x01 \x01(\t\x12*\n\tvariables\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x1a\x07\n\x05Pause\x1a\x08\n\x06Resume\x1a\x08\n\x06\x43\x61ncel\x1a\r\n\x0bToggleLightB\t\n\x07\x63ommand\".\n\x06\x43onfig\x12\x10\n\x08robot_ip\x18\x01 \x01(\t\x12\x12\n\nrobot_port\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.opentrons2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=149
  _globals['_COMMAND']._serialized_end=753
  _globals['_COMMAND_RUNPROGRAM']._serialized_start=618
  _globals['_COMMAND_RUNPROGRAM']._serialized_end=698
  _globals['_COMMAND_PAUSE']._serialized_start=700
  _globals['_COMMAND_PAUSE']._serialized_end=707
  _globals['_COMMAND_RESUME']._serialized_start=709
  _globals['_COMMAND_RESUME']._serialized_end=717
  _globals['_COMMAND_CANCEL']._serialized_start=719
  _globals['_COMMAND_CANCEL']._serialized_end=727
  _globals['_COMMAND_TOGGLELIGHT']._serialized_start=729
  _globals['_COMMAND_TOGGLELIGHT']._serialized_end=742
  _globals['_CONFIG']._serialized_start=755
  _globals['_CONFIG']._serialized_end=801
# @@protoc_insertion_point(module_scope)
