# Derived from galago-tools interfaces/tools/grpc_interfaces/plateloc.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/plateloc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/plateloc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:rhylthyme_galago/_gen/tools/grpc_interfaces/plateloc.proto\x12\x32\x63om.science.foundry.tools.grpc_interfaces.plateloc\"\xce\x06\n\x07\x43ommand\x12P\n\x04seal\x18\x01 \x01(\x0b\x32@.com.science.foundry.tools.grpc_interfaces.plateloc.Command.SealH\x00\x12\x65\n\x0fset_temperature\x18\x02 \x01(\x0b\x32J.com.science.foundry.tools.grpc_interfaces.plateloc.Command.SetTemperatureH\x00\x12`\n\rset_seal_time\x18\x03 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.plateloc.Command.SetSealTimeH\x00\x12r\n\x16get_actual_temperature\x18\x04 \x01(\x0b\x32P.com.science.foundry.tools.grpc_interfaces.plateloc.Command.GetActualTemperatureH\x00\x12W\n\x08stage_in\x18\x05 \x01(\x0b\x32\x43.com.science.foundry.tools.grpc_interfaces.plateloc.Command.StageInH\x00\x12Y\n\tstage_out\x18\x06 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.plateloc.Command.StageOutH\x00\x12g\n\x10show_diagnostics\x18\x07 \x01(\x0b\x32K.com.science.foundry.tools.grpc_interfaces.plateloc.Command.ShowDiagsDialogH\x00\x1a\x06\n\x04Seal\x1a%\n\x0eSetTemperature\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\x1a\x1b\n\x0bSetSealTime\x12\x0c\n\x04time\x18\x01 \x01(\x02\x1a\x16\n\x14GetActualTemperature\x1a\t\n\x07StageIn\x1a\n\n\x08StageOut\x1a\x11\n\x0fShowDiagsDialogB\t\n\x07\x63ommand\"\x19\n\x06\x43onfig\x12\x0f\n\x07profile\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.plateloc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=115
  _globals['_COMMAND']._serialized_end=961
  _globals['_COMMAND_SEAL']._serialized_start=810
  _globals['_COMMAND_SEAL']._serialized_end=816
  _globals['_COMMAND_SETTEMPERATURE']._serialized_start=818
  _globals['_COMMAND_SETTEMPERATURE']._serialized_end=855
  _globals['_COMMAND_SETSEALTIME']._serialized_start=857
  _globals['_COMMAND_SETSEALTIME']._serialized_end=884
  _globals['_COMMAND_GETACTUALTEMPERATURE']._serialized_start=886
  _globals['_COMMAND_GETACTUALTEMPERATURE']._serialized_end=908
  _globals['_COMMAND_STAGEIN']._serialized_start=910
  _globals['_COMMAND_STAGEIN']._serialized_end=919
  _globals['_COMMAND_STAGEOUT']._serialized_start=921
  _globals['_COMMAND_STAGEOUT']._serialized_end=931
  _globals['_COMMAND_SHOWDIAGSDIALOG']._serialized_start=933
  _globals['_COMMAND_SHOWDIAGSDIALOG']._serialized_end=950
  _globals['_CONFIG']._serialized_start=963
  _globals['_CONFIG']._serialized_end=988
# @@protoc_insertion_point(module_scope)
