# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/plr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/plr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5rhylthyme_galago/_gen/tools/grpc_interfaces/plr.proto\x12-com.science.foundry.tools.grpc_interfaces.plr\"\xb8\x02\n\x07\x43ommand\x12\x61\n\x10run_local_script\x18\x01 \x01(\x0b\x32\x45.com.science.foundry.tools.grpc_interfaces.plr.Command.RunLocalScriptH\x00\x12V\n\nrun_script\x18\x02 \x01(\x0b\x32@.com.science.foundry.tools.grpc_interfaces.plr.Command.RunScriptH\x00\x1a\x30\n\x0eRunLocalScript\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x62locking\x18\x02 \x01(\x08\x1a\x35\n\tRunScript\x12\x16\n\x0escript_content\x18\x01 \x01(\t\x12\x10\n\x08\x62locking\x18\x02 \x01(\x08\x42\t\n\x07\x63ommand\"\x1c\n\x06\x43onfig\x12\x12\n\npython_exe\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.plr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=105
  _globals['_COMMAND']._serialized_end=417
  _globals['_COMMAND_RUNLOCALSCRIPT']._serialized_start=303
  _globals['_COMMAND_RUNLOCALSCRIPT']._serialized_end=351
  _globals['_COMMAND_RUNSCRIPT']._serialized_start=353
  _globals['_COMMAND_RUNSCRIPT']._serialized_end=406
  _globals['_CONFIG']._serialized_start=419
  _globals['_CONFIG']._serialized_end=447
# @@protoc_insertion_point(module_scope)
