# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/spectramax.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/spectramax.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<rhylthyme_galago/_gen/tools/grpc_interfaces/spectramax.proto\x12\x34\x63om.science.foundry.tools.grpc_interfaces.spectramax\"\x91\x03\n\x07\x43ommand\x12_\n\x0bopen_drawer\x18\x01 \x01(\x0b\x32H.com.science.foundry.tools.grpc_interfaces.spectramax.Command.OpenDrawerH\x00\x12\x61\n\x0c\x63lose_drawer\x18\x02 \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.spectramax.Command.CloseDrawerH\x00\x12]\n\nstart_read\x18\x03 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.spectramax.Command.StartReadH\x00\x1a\x0c\n\nOpenDrawer\x1a\r\n\x0b\x43loseDrawer\x1a;\n\tStartRead\x12\x15\n\rprotocol_file\x18\x01 \x01(\t\x12\x17\n\x0f\x65xperiment_name\x18\x02 \x01(\tB\t\n\x07\x63ommand\"6\n\x06\x43onfig\x12\x14\n\x0cprotocol_dir\x18\x01 \x01(\t\x12\x16\n\x0e\x65xperiment_dir\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.spectramax_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=119
  _globals['_COMMAND']._serialized_end=520
  _globals['_COMMAND_OPENDRAWER']._serialized_start=421
  _globals['_COMMAND_OPENDRAWER']._serialized_end=433
  _globals['_COMMAND_CLOSEDRAWER']._serialized_start=435
  _globals['_COMMAND_CLOSEDRAWER']._serialized_end=448
  _globals['_COMMAND_STARTREAD']._serialized_start=450
  _globals['_COMMAND_STARTREAD']._serialized_end=509
  _globals['_CONFIG']._serialized_start=522
  _globals['_CONFIG']._serialized_end=576
# @@protoc_insertion_point(module_scope)
