# Derived from galago-tools interfaces/tools/grpc_interfaces/tool_driver.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
from google.protobuf import empty_pb2 as _empty_pb2
from rhylthyme_galago._gen.tools.grpc_interfaces import tool_base_pb2 as _tool_base_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
