# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/toolbox.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/toolbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9rhylthyme_galago/_gen/tools/grpc_interfaces/toolbox.proto\x12\x31\x63om.science.foundry.tools.grpc_interfaces.toolbox\x1a\x1cgoogle/protobuf/struct.proto\"\xd0\x07\n\x07\x43ommand\x12`\n\rslack_message\x18\x01 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.toolbox.Command.SlackMessageH\x00\x12Z\n\nrun_script\x18\x02 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.toolbox.Command.RunScriptH\x00\x12\x65\n\x10send_slack_alert\x18\x03 \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.toolbox.Command.SendSlackAlertH\x00\x12p\n\x16\x63lear_last_slack_alert\x18\x04 \x01(\x0b\x32N.com.science.foundry.tools.grpc_interfaces.toolbox.Command.ClearLastSlackAlertH\x00\x12_\n\rwrite_to_json\x18\x05 \x01(\x0b\x32\x46.com.science.foundry.tools.grpc_interfaces.toolbox.Command.WriteToJsonH\x00\x12\x61\n\x0etext_to_speech\x18\x06 \x01(\x0b\x32G.com.science.foundry.tools.grpc_interfaces.toolbox.Command.TextToSpeechH\x00\x1aP\n\x0bWriteToJson\x12.\n\rstruct_object\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x11\n\tfile_path\x18\x02 \x01(\t\x1a\x1f\n\x0cSlackMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x1a\x1c\n\x0cTextToSpeech\x12\x0c\n\x04text\x18\x01 \x01(\t\x1a\x35\n\tRunScript\x12\x16\n\x0escript_content\x18\x01 \x01(\t\x12\x10\n\x08\x62locking\x18\x02 \x01(\x08\x1aY\n\x0eSendSlackAlert\x12\x10\n\x08workcell\x18\x01 \x01(\t\x12\x0c\n\x04tool\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x1a\x15\n\x13\x43learLastSlackAlert\x1a%\n\x0eValidateFolder\x12\x13\n\x0b\x66older_path\x18\x01 \x01(\tB\t\n\x07\x63ommand\"\x08\n\x06\x43onfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.toolbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=143
  _globals['_COMMAND']._serialized_end=1119
  _globals['_COMMAND_WRITETOJSON']._serialized_start=757
  _globals['_COMMAND_WRITETOJSON']._serialized_end=837
  _globals['_COMMAND_SLACKMESSAGE']._serialized_start=839
  _globals['_COMMAND_SLACKMESSAGE']._serialized_end=870
  _globals['_COMMAND_TEXTTOSPEECH']._serialized_start=872
  _globals['_COMMAND_TEXTTOSPEECH']._serialized_end=900
  _globals['_COMMAND_RUNSCRIPT']._serialized_start=902
  _globals['_COMMAND_RUNSCRIPT']._serialized_end=955
  _globals['_COMMAND_SENDSLACKALERT']._serialized_start=957
  _globals['_COMMAND_SENDSLACKALERT']._serialized_end=1046
  _globals['_COMMAND_CLEARLASTSLACKALERT']._serialized_start=1048
  _globals['_COMMAND_CLEARLASTSLACKALERT']._serialized_end=1069
  _globals['_COMMAND_VALIDATEFOLDER']._serialized_start=1071
  _globals['_COMMAND_VALIDATEFOLDER']._serialized_end=1108
  _globals['_CONFIG']._serialized_start=1121
  _globals['_CONFIG']._serialized_end=1129
# @@protoc_insertion_point(module_scope)
