# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/tool_driver.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/tool_driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from rhylthyme_galago._gen.tools.grpc_interfaces import tool_base_pb2 as rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=rhylthyme_galago/_gen/tools/grpc_interfaces/tool_driver.proto\x12)com.science.foundry.tools.grpc_interfaces\x1a\x1bgoogle/protobuf/empty.proto\x1a;rhylthyme_galago/_gen/tools/grpc_interfaces/tool_base.proto2\xf6\x03\n\nToolDriver\x12[\n\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x36.com.science.foundry.tools.grpc_interfaces.StatusReply\x12\x84\x01\n\x0e\x45xecuteCommand\x12\x32.com.science.foundry.tools.grpc_interfaces.Command\x1a>.com.science.foundry.tools.grpc_interfaces.ExecuteCommandReply\x12\x88\x01\n\x10\x45stimateDuration\x12\x32.com.science.foundry.tools.grpc_interfaces.Command\x1a@.com.science.foundry.tools.grpc_interfaces.EstimateDurationReply\x12y\n\tConfigure\x12\x31.com.science.foundry.tools.grpc_interfaces.Config\x1a\x39.com.science.foundry.tools.grpc_interfaces.ConfigureReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.tool_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLDRIVER']._serialized_start=199
  _globals['_TOOLDRIVER']._serialized_end=701
# @@protoc_insertion_point(module_scope)
