# Derived from galago-tools interfaces/tools/grpc_interfaces/tool_driver.proto
# (https://github.com/sciencecorp/galago-tools), Copyright 2025 - Science
# Corporation, licensed under the Apache License, Version 2.0; see NOTICE.
# Generated by rhylthyme-galago scripts/refresh_protos.py; modified: proto
# import paths moved under rhylthyme_galago._gen before generation.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from rhylthyme_galago._gen.tools.grpc_interfaces import tool_base_pb2 as rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rhylthyme_galago/_gen/tools/grpc_interfaces/tool_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolDriverStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/com.science.foundry.tools.grpc_interfaces.ToolDriver/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/com.science.foundry.tools.grpc_interfaces.ToolDriver/ExecuteCommand',
                request_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Command.SerializeToString,
                response_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.ExecuteCommandReply.FromString,
                _registered_method=True)
        self.EstimateDuration = channel.unary_unary(
                '/com.science.foundry.tools.grpc_interfaces.ToolDriver/EstimateDuration',
                request_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Command.SerializeToString,
                response_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.EstimateDurationReply.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/com.science.foundry.tools.grpc_interfaces.ToolDriver/Configure',
                request_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Config.SerializeToString,
                response_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.ConfigureReply.FromString,
                _registered_method=True)


class ToolDriverServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateDuration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.StatusReply.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Command.FromString,
                    response_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.ExecuteCommandReply.SerializeToString,
            ),
            'EstimateDuration': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateDuration,
                    request_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Command.FromString,
                    response_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.EstimateDurationReply.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Config.FromString,
                    response_serializer=rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.ConfigureReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.science.foundry.tools.grpc_interfaces.ToolDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.science.foundry.tools.grpc_interfaces.ToolDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolDriver:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.science.foundry.tools.grpc_interfaces.ToolDriver/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.science.foundry.tools.grpc_interfaces.ToolDriver/ExecuteCommand',
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Command.SerializeToString,
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.ExecuteCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateDuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.science.foundry.tools.grpc_interfaces.ToolDriver/EstimateDuration',
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Command.SerializeToString,
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.EstimateDurationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.science.foundry.tools.grpc_interfaces.ToolDriver/Configure',
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.Config.SerializeToString,
            rhylthyme__galago_dot___gen_dot_tools_dot_grpc__interfaces_dot_tool__base__pb2.ConfigureReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
