# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/vcode.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/vcode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7rhylthyme_galago/_gen/tools/grpc_interfaces/vcode.proto\x12/com.science.foundry.tools.grpc_interfaces.vcode\"\xd0\x07\n\x07\x43ommand\x12M\n\x04home\x18\x01 \x01(\x0b\x32=.com.science.foundry.tools.grpc_interfaces.vcode.Command.HomeH\x00\x12O\n\x05print\x18\x02 \x01(\x0b\x32>.com.science.foundry.tools.grpc_interfaces.vcode.Command.PrintH\x00\x12\x61\n\x0fprint_and_apply\x18\x03 \x01(\x0b\x32\x46.com.science.foundry.tools.grpc_interfaces.vcode.Command.PrintAndApplyH\x00\x12X\n\nrotate_180\x18\x04 \x01(\x0b\x32\x42.com.science.foundry.tools.grpc_interfaces.vcode.Command.Rotate180H\x00\x12\\\n\x0crotate_stage\x18\x05 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.vcode.Command.RotateStageH\x00\x12\x64\n\x10show_diagnostics\x18\x06 \x01(\x0b\x32H.com.science.foundry.tools.grpc_interfaces.vcode.Command.ShowDiagsDialogH\x00\x1a\x1c\n\x0bRotateStage\x12\r\n\x05\x61ngle\x18\x01 \x01(\x05\x1a\x06\n\x04Home\x1a\xac\x01\n\rPrintAndApply\x12\x13\n\x0b\x66ormat_name\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x12\n\ndrop_stage\x18\x03 \x01(\x08\x12\x0f\n\x07\x66ield_0\x18\x04 \x01(\t\x12\x0f\n\x07\x66ield_1\x18\x05 \x01(\t\x12\x0f\n\x07\x66ield_2\x18\x06 \x01(\t\x12\x0f\n\x07\x66ield_3\x18\x07 \x01(\t\x12\x0f\n\x07\x66ield_4\x18\x08 \x01(\t\x12\x0f\n\x07\x66ield_5\x18\t \x01(\t\x1a\x1f\n\tDropStage\x12\x12\n\ndrop_stage\x18\x01 \x01(\x08\x1a\x82\x01\n\x05Print\x12\x13\n\x0b\x66ormat_name\x18\x01 \x01(\t\x12\x0f\n\x07\x66ield_0\x18\x02 \x01(\t\x12\x0f\n\x07\x66ield_1\x18\x03 \x01(\t\x12\x0f\n\x07\x66ield_2\x18\x04 \x01(\t\x12\x0f\n\x07\x66ield_3\x18\x05 \x01(\t\x12\x0f\n\x07\x66ield_4\x18\x06 \x01(\t\x12\x0f\n\x07\x66ield_5\x18\x07 \x01(\t\x1a\x0b\n\tRotate180\x1a\x11\n\x0fShowDiagsDialogB\t\n\x07\x63ommand\"\x19\n\x06\x43onfig\x12\x0f\n\x07profile\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.vcode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=109
  _globals['_COMMAND']._serialized_end=1085
  _globals['_COMMAND_ROTATESTAGE']._serialized_start=665
  _globals['_COMMAND_ROTATESTAGE']._serialized_end=693
  _globals['_COMMAND_HOME']._serialized_start=695
  _globals['_COMMAND_HOME']._serialized_end=701
  _globals['_COMMAND_PRINTANDAPPLY']._serialized_start=704
  _globals['_COMMAND_PRINTANDAPPLY']._serialized_end=876
  _globals['_COMMAND_DROPSTAGE']._serialized_start=878
  _globals['_COMMAND_DROPSTAGE']._serialized_end=909
  _globals['_COMMAND_PRINT']._serialized_start=912
  _globals['_COMMAND_PRINT']._serialized_end=1042
  _globals['_COMMAND_ROTATE180']._serialized_start=1044
  _globals['_COMMAND_ROTATE180']._serialized_end=1055
  _globals['_COMMAND_SHOWDIAGSDIALOG']._serialized_start=1057
  _globals['_COMMAND_SHOWDIAGSDIALOG']._serialized_end=1074
  _globals['_CONFIG']._serialized_start=1087
  _globals['_CONFIG']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
