# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rhylthyme_galago/_gen/tools/grpc_interfaces/xpeel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rhylthyme_galago/_gen/tools/grpc_interfaces/xpeel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7rhylthyme_galago/_gen/tools/grpc_interfaces/xpeel.proto\x12/com.science.foundry.tools.grpc_interfaces.xpeel\"\xa2\x04\n\x07\x43ommand\x12M\n\x04peel\x18\x01 \x01(\x0b\x32=.com.science.foundry.tools.grpc_interfaces.xpeel.Command.PeelH\x00\x12\\\n\x0c\x63heck_status\x18\x02 \x01(\x0b\x32\x44.com.science.foundry.tools.grpc_interfaces.xpeel.Command.CheckStatusH\x00\x12O\n\x05reset\x18\x03 \x01(\x0b\x32>.com.science.foundry.tools.grpc_interfaces.xpeel.Command.ResetH\x00\x12S\n\x07restart\x18\x04 \x01(\x0b\x32@.com.science.foundry.tools.grpc_interfaces.xpeel.Command.RestartH\x00\x12g\n\x12get_remaining_tape\x18\x05 \x01(\x0b\x32I.com.science.foundry.tools.grpc_interfaces.xpeel.Command.GetRemainingTapeH\x00\x1a\x19\n\x04Peel\x12\x11\n\tthreshold\x18\x01 \x01(\x05\x1a\r\n\x0b\x43heckStatus\x1a\x07\n\x05Reset\x1a\t\n\x07Restart\x1a\x12\n\x10GetRemainingTapeB\t\n\x07\x63ommand\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x63om_port\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rhylthyme_galago._gen.tools.grpc_interfaces.xpeel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=109
  _globals['_COMMAND']._serialized_end=655
  _globals['_COMMAND_PEEL']._serialized_start=564
  _globals['_COMMAND_PEEL']._serialized_end=589
  _globals['_COMMAND_CHECKSTATUS']._serialized_start=591
  _globals['_COMMAND_CHECKSTATUS']._serialized_end=604
  _globals['_COMMAND_RESET']._serialized_start=606
  _globals['_COMMAND_RESET']._serialized_end=613
  _globals['_COMMAND_RESTART']._serialized_start=615
  _globals['_COMMAND_RESTART']._serialized_end=624
  _globals['_COMMAND_GETREMAININGTAPE']._serialized_start=626
  _globals['_COMMAND_GETREMAININGTAPE']._serialized_end=644
  _globals['_CONFIG']._serialized_start=657
  _globals['_CONFIG']._serialized_end=683
# @@protoc_insertion_point(module_scope)
